name: Check dist

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain dist/)" ]; then
            echo "::error::The dist folder is not up-to-date with source files."
            echo "Please run 'bun run build' and commit the changes to dist/"
            echo ""
            echo "Changed files:"
            git status --porcelain dist/
            echo ""
            echo "Diff:"
            git diff dist/
            exit 1
          else
            echo "✅ The dist folder is up-to-date"
          fi
